#name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker build -t ghcr.io/hatabech/task22:1.0 .
      - run: docker push ghcr.io/hatabech/task22:1.0
      - run: ssh -o "StrictHostKeyCheking no" 'hatabech-task22-j1tapeyazy6#mSk6ABTiHM3iSoy3gjPNaTLiQ-6Tw8Z9@hatabech-task22-j1tapeyazy6.ssh.ws-eu106.gitpod.io'
